#' @include provider-openai.R
#' @include content.R
NULL

# https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#chat-completions

#' Chat with a model hosted on Azure OpenAI
#'
#' @description
#' The [Azure OpenAI server](https://azure.microsoft.com/en-us/products/ai-services/openai-service)
#' hosts a number of open source models as well as proprietary models
#' from OpenAI.
#'
#' @param endpoint Azure OpenAI endpoint url with protocol and hostname, i.e.
#'  `https://{your-resource-name}.openai.azure.com`. Defaults to using the
#'   value of the `AZURE_OPENAI_ENDPOINT` envinronment variable.
#' @param deployment_id Deployment id for the model you want to use.
#' @param api_version The API version to use.
#' @param api_key An API key to use for authentication. You generally should not
#'   supply this directly, but instead set the `AZURE_OPENAI_API_KEY`
#'   environment variable.
#' @param token A literal Azure token to use for authentication.
#' @param credentials A list of authentication headers to pass into
#'   [`httr2::req_headers()`], a function that returns them, or `NULL` to use
#'   `token` or `api_key` to generate these headers instead. This is an escape
#'   hatch that allows users to incorporate Azure credentials generated by other
#'   packages into \pkg{ellmer}, or to manage the lifetime of credentials that
#'   need to be refreshed.
#' @inheritParams chat_openai
#' @inherit chat_openai return
#' @export
#' @examples
#' \dontrun{
#' chat <- chat_azure(deployment_id = "gpt-4o-mini")
#' chat$chat("Tell me three jokes about statisticians")
#' }
chat_azure <- function(endpoint = azure_endpoint(),
                       deployment_id,
                       api_version = NULL,
                       system_prompt = NULL,
                       turns = NULL,
                       api_key = NULL,
                       token = NULL,
                       credentials = NULL,
                       api_args = list(),
                       echo = c("none", "text", "all")) {
  check_string(endpoint)
  check_string(deployment_id)
  api_version <- set_default(api_version, "2024-06-01")
  turns <- normalize_turns(turns, system_prompt)
  check_exclusive(api_key, token, credentials, .require = FALSE)
  check_string(api_key, allow_null = TRUE)
  check_string(token, allow_null = TRUE)
  echo <- check_echo(echo)
 if (is_list(credentials)) {
    static_credentials <- force(credentials)
    credentials <- function() static_credentials
  }
  check_function(credentials, allow_null = TRUE)
  credentials <- credentials %||% default_azure_credentials(api_key, token)

  provider <- ProviderAzure(
    endpoint = endpoint,
    deployment_id = deployment_id,
    api_version = api_version,
    credentials = credentials,
    extra_args = api_args
  )
  Chat$new(provider = provider, turns = turns, echo = echo)
}

ProviderAzure <- new_class(
  "ProviderAzure",
  parent = ProviderOpenAI,
  constructor = function(endpoint, deployment_id, api_version, credentials,
                         extra_args = list()) {
    new_object(
      ProviderOpenAI(
        base_url = paste0(endpoint, "/openai/deployments/", deployment_id),
        model = deployment_id,
        api_key = "",
        extra_args = extra_args
      ),
      api_version = api_version,
      credentials = credentials
    )
  },
  properties = list(
    credentials = class_function | NULL,
    api_version = prop_string()
  )
)

# https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/switching-endpoints#api-key
azure_endpoint <- function() {
  key_get("AZURE_OPENAI_ENDPOINT")
}

# https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#chat-completions
method(chat_request, ProviderAzure) <- function(provider,
                                                stream = TRUE,
                                                turns = list(),
                                                tools = list(),
                                                type = NULL,
                                                extra_args = list()) {

  req <- request(provider@base_url)
  req <- req_url_path_append(req, "/chat/completions")
  req <- req_url_query(req, `api-version` = provider@api_version)
  # Note: could use req_headers_redacted() here but it requires a very new
  # httr2 version.
  req <- req_headers(
    req,
    !!!provider@credentials(),
    .redact = c("api-key", "Authorization")
  )
  req <- req_retry(req, max_tries = 2)
  req <- req_error(req, body = function(resp) resp_body_json(resp)$message)

  messages <- compact(unlist(as_json(provider, turns), recursive = FALSE))
  tools <- as_json(provider, unname(tools))
  extra_args <- utils::modifyList(provider@extra_args, extra_args)

  if (!is.null(type)) {
    response_format <- list(
      type = "json_schema",
      json_schema = list(
        name = "structured_data",
        schema = as_json(provider, type),
        strict = TRUE
      )
    )
  } else {
    response_format <- NULL
  }

  data <- compact(list2(
    messages = messages,
    model = provider@model,
    seed = provider@seed,
    stream = stream,
    stream_options = if (stream) list(include_usage = TRUE),
    tools = tools,
    response_format = response_format,
    !!!extra_args
  ))
  req <- req_body_json(req, data)

  req
}

default_azure_credentials <- function(api_key = NULL, token = NULL) {
  api_key <- api_key %||% Sys.getenv("AZURE_OPENAI_API_KEY")
  if (nchar(api_key)) {
    return(function() list(`api-key` = api_key))
  }

  if (!is.null(token)) {
    return(function() list(Authorization = paste("Bearer", token)))
  }

  if (is_testing()) {
    testthat::skip("no Azure credentials available")
  }

  cli::cli_abort("No Azure credentials are available.")
}
