# Generated by data-raw/prices.R: do not edit by hand

# Bedrock models that the Converse API can't serve, and the API to use
# instead. Anything not listed here is assumed to work with Converse.
aws_bedrock_model_apis <- c(
  "anthropic.claude-mythos-5" = "messages",
  "anthropic.claude-mythos-preview" = "messages",
  "google.gemma-4-26b-a4b" = "responses",
  "google.gemma-4-31b" = "responses",
  "google.gemma-4-e2b" = "responses",
  "openai.gpt-5.4" = "responses",
  "openai.gpt-5.5" = "responses",
  "openai.gpt-5.6-cyber" = "responses",
  "openai.gpt-daybreak-blue-5.6-sol" = "responses",
  "us-gov-east-1/openai.gpt-5.4" = "responses",
  "us-gov-east-1/xai.grok-4.6" = "responses",
  "us-gov-west-1/google.gemma-4-26b-a4b" = "responses",
  "us-gov-west-1/google.gemma-4-31b" = "responses",
  "us-gov-west-1/google.gemma-4-e2b" = "responses",
  "us-gov-west-1/openai.gpt-5.4" = "responses",
  "us-gov-west-1/openai.gpt-5.6-luna" = "responses",
  "us-gov-west-1/openai.gpt-5.6-terra" = "responses",
  "us-gov-west-1/xai.grok-4.3" = "responses",
  "us-gov-west-1/xai.grok-4.6" = "responses",
  "xai.grok-4.3" = "responses"
)
