#' @include tools-def.R
#' @include as-json.R

ToolBuiltIn <- new_class(
  "ToolBuiltIn",
  properties = list(
    name = prop_string(),
    description = prop_string(default = ""),
    annotations = class_list,
    json = class_any
  )
)

method(as_json, list(Provider, ToolBuiltIn)) <- function(provider, x, ...) {
  x@json
}

#' Built-in web activity content
#'
#' @description
#' `r lifecycle::badge("experimental")`
#'
#' These public content records describe provider-managed web searches and
#' fetches. They are generated by ellmer when a built-in web tool runs and can
#' be consumed by user interfaces without parsing provider response data.
#'
#' @param query The web search query.
#' @param sources A list of [WebSource] objects returned by a search.
#' @param url The URL requested or fetched. Fetch responses may use `NULL` when
#'   the provider reports a failure without identifying the URL.
#' @param status A normalized fetch outcome: `"success"`, `"error"`, or `NULL`
#'   when the provider does not report an outcome.
#' @param extra Raw provider-specific metadata, or `NULL`.
#' @return An S7 object that inherits from [Content].
#' @name ContentWebActivity
NULL

# Web search ---------------------------------------------------------------

#' @rdname ContentWebActivity
#' @export
ContentToolRequestSearch <- new_class(
  "ContentToolRequestSearch",
  parent = Content,
  properties = list(
    query = prop_string(),
    extra = NULL | class_list
  )
)
method(format, ContentToolRequestSearch) <- function(x, ...) {
  cli::format_inline("[{.strong web search request}]: {.str {x@query}}")
}
#' @rdname ContentWebActivity
#' @export
ContentToolResponseSearch <- new_class(
  "ContentToolResponseSearch",
  parent = Content,
  properties = list(
    sources = prop_list_of(WebSource),
    extra = NULL | class_list
  )
)
method(format, ContentToolResponseSearch) <- function(x, ...) {
  paste0(
    cli::format_inline("[{.strong web search results}]:\n"),
    paste0("* ", map_chr(x@sources, format), "\n", collapse = "")
  )
}

# Web fetch -------------------------------------------------------------------

#' @rdname ContentWebActivity
#' @export
ContentToolRequestFetch <- new_class(
  "ContentToolRequestFetch",
  parent = Content,
  properties = list(
    url = prop_string(),
    extra = NULL | class_list
  )
)
method(format, ContentToolRequestFetch) <- function(x, ...) {
  cli::format_inline("[{.strong web fetch request}]: {.url {x@url}}")
}
#' @rdname ContentWebActivity
#' @export
ContentToolResponseFetch <- new_class(
  "ContentToolResponseFetch",
  parent = Content,
  properties = list(
    url = prop_string(allow_null = TRUE),
    status = new_property(
      class = NULL | class_character,
      default = NULL,
      validator = function(value) {
        if (
          is.null(value) ||
            identical(value, "success") ||
            identical(value, "error")
        ) {
          return()
        }
        'must be one of "success", "error", or NULL.'
      }
    ),
    extra = NULL | class_list
  )
)
method(format, ContentToolResponseFetch) <- function(x, ...) {
  cli::format_inline(
    "[{.strong web fetch result}]: {.url {x@url %||% '[unknown URL]'}}"
  )
}

# Provider serialization --------------------------------------------------

method(as_json, list(Provider, ContentToolRequestSearch)) <- function(
  provider,
  x,
  ...
) {
  NULL
}

method(as_json, list(Provider, ContentToolResponseSearch)) <- function(
  provider,
  x,
  ...
) {
  NULL
}

method(as_json, list(Provider, ContentToolRequestFetch)) <- function(
  provider,
  x,
  ...
) {
  NULL
}

method(as_json, list(Provider, ContentToolResponseFetch)) <- function(
  provider,
  x,
  ...
) {
  NULL
}

method(as_json, list(ProviderAnthropic, ContentToolRequestSearch)) <- function(
  provider,
  x,
  ...
) {
  anthropic_replay_annotation(x)
}

method(as_json, list(ProviderAnthropic, ContentToolResponseSearch)) <- function(
  provider,
  x,
  ...
) {
  anthropic_replay_annotation(x)
}

method(as_json, list(ProviderAnthropic, ContentToolRequestFetch)) <- function(
  provider,
  x,
  ...
) {
  anthropic_replay_annotation(x)
}

method(as_json, list(ProviderAnthropic, ContentToolResponseFetch)) <- function(
  provider,
  x,
  ...
) {
  anthropic_replay_annotation(x)
}

method(as_json, list(ProviderOpenAI, ContentToolRequestSearch)) <- function(
  provider,
  x,
  ...
) {
  openai_replay_annotation(x)
}

method(as_json, list(ProviderOpenAI, ContentToolRequestFetch)) <- function(
  provider,
  x,
  ...
) {
  openai_replay_annotation(x)
}

openai_replay_annotation <- function(content) {
  if (
    !is.null(content@extra) &&
      identical(content@extra$type, "web_search_call")
  ) {
    content@extra
  }
}
